spring.application.name=motor_misiones_y_Recompensas

#MYSQL Configuration
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://127.0.0.1:3306/quest_reward_db?createDatabaseIfNotExist=true
spring.datasource.username=tomi
spring.datasource.password=44987089

#Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.dialect=org.hibernate.dialect.MySQLDialect

#Swagger
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs